//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnDBFirst.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LearnDBFirstEntities : DbContext
    {
        public LearnDBFirstEntities()
            : base("name=LearnDBFirstEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<BookDetail> BookDetails { get; set; }
        public virtual DbSet<Publisher> Publishers { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<BooksAuthor> BooksAuthors { get; set; }
        public virtual DbSet<vBook> vBooks { get; set; }
    
        public virtual ObjectResult<string> spGetBooks(string authorFirstName, string authorLastName)
        {
            var authorFirstNameParameter = authorFirstName != null ?
                new ObjectParameter("authorFirstName", authorFirstName) :
                new ObjectParameter("authorFirstName", typeof(string));
    
            var authorLastNameParameter = authorLastName != null ?
                new ObjectParameter("authorLastName", authorLastName) :
                new ObjectParameter("authorLastName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spGetBooks", authorFirstNameParameter, authorLastNameParameter);
        }
    }
}
